from __future__ import annotations

from enum import Enum


class WriteStateName(str, Enum):
    FLAGS_CONTROLS = 'FLAGS_CONTROLS'
    FLAGS_PHYSICS = 'FLAGS_PHYSICS'

    MOTOR_LEFT = 'MOTOR_LEFT'
    MOTOR_RIGHT = 'MOTOR_RIGHT'

    L2_EFFECT_MODE = 'L2_EFFECT_MODE'
    L2_EFFECT_PARAM1 = 'L2_EFFECT_PARAM1'
    L2_EFFECT_PARAM2 = 'L2_EFFECT_PARAM2'
    L2_EFFECT_PARAM3 = 'L2_EFFECT_PARAM3'
    L2_EFFECT_PARAM4 = 'L2_EFFECT_PARAM4'
    L2_EFFECT_PARAM5 = 'L2_EFFECT_PARAM5'
    L2_EFFECT_PARAM6 = 'L2_EFFECT_PARAM6'
    L2_EFFECT_PARAM7 = 'L2_EFFECT_PARAM7'
    R2_EFFECT_MODE = 'R2_EFFECT_MODE'
    R2_EFFECT_PARAM1 = 'R2_EFFECT_PARAM1'
    R2_EFFECT_PARAM2 = 'R2_EFFECT_PARAM2'
    R2_EFFECT_PARAM3 = 'R2_EFFECT_PARAM3'
    R2_EFFECT_PARAM4 = 'R2_EFFECT_PARAM4'
    R2_EFFECT_PARAM5 = 'R2_EFFECT_PARAM5'
    R2_EFFECT_PARAM6 = 'R2_EFFECT_PARAM6'
    R2_EFFECT_PARAM7 = 'R2_EFFECT_PARAM7'

    LIGHTBAR = 'LIGHTBAR'
    LIGHTBAR_RED = 'LIGHTBAR_RED'
    LIGHTBAR_GREEN = 'LIGHTBAR_GREEN'
    LIGHTBAR_BLUE = 'LIGHTBAR_BLUE'
    LIGHTBAR_ON_OFF = 'LIGHTBAR_ON_OFF'
    LIGHTBAR_PULSE_OPTIONS = 'LIGHTBAR_PULSE_OPTIONS'

    LED_OPTIONS = 'LED_OPTIONS'

    PLAYER_LEDS = "PLAYER_LEDS"
    PLAYER_LEDS_BRIGHTNESS = 'PLAYER_LEDS_BRIGHTNESS'
    PLAYER_LEDS_ENABLE = 'PLAYER_LEDS_ENABLE'

    MICROPHONE = "MICROPHONE"
    MICROPHONE_LED = 'MICROPHONE_LED'
    MICROPHONE_MUTE = 'MICROPHONE_MUTE'
